// client/src/App.jsx
import { useState, useEffect } from 'react';
import { io } from 'socket.io-client';
import GameScreen from './components/GameScreen';
import GameEndScreen from './components/GameEndScreen';
import './App.css';

const socket = io('http://localhost:3001');

function App() {
  const [connected, setConnected] = useState(false);
  const [view, setView] = useState('MENU');
  const [nickname, setNickname] = useState('');
  const [roomCode, setRoomCode] = useState('');
  const [currentRoom, setCurrentRoom] = useState(null);
  const [playerId, setPlayerId] = useState(null);
  const [sentenceCount, setSentenceCount] = useState(15);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [countdown, setCountdown] = useState(null);
  const [sentences, setSentences] = useState([]);
  const [gameEndData, setGameEndData] = useState(null);
  const [userRole, setUserRole] = useState(null);

  useEffect(() => {
    const handleGameEnded = (data) => {
      console.log('App.jsx received game_ended:', data);
      
      setCurrentRoom(prev => {
        if (!prev) return prev;
        return {
          ...prev,
          players: data.finalStats,
          status: 'FINISHED'
        };
      });
      
      setGameEndData(data);
      
      setTimeout(() => {
        setView('FINISHED');
      }, 6200);
    };

    socket.on('game_ended', handleGameEnded);

    return () => {
      socket.off('game_ended', handleGameEnded);
    };
  }, []);

  useEffect(() => {
    socket.on('connect', () => {
      console.log('CONNECTION ESTABLISHED');
      setConnected(true);
    });

    socket.on('disconnect', () => {
      console.log('CONNECTION TERMINATED');
      setConnected(false);
    });

    socket.on('settings_updated', (data) => {
      console.log('SETTINGS_UPDATED:', data);
      if (currentRoom) {
        setCurrentRoom({
          ...currentRoom,
          settings: {
            ...currentRoom.settings,
            sentenceCount: data.sentenceCount
          }
        });
      }
    });

    socket.on('player_joined', (data) => {
      console.log('PLAYER_JOINED:', data);
      if (currentRoom && data.updatedPlayers) {
        setCurrentRoom({
          ...currentRoom,
          players: data.updatedPlayers.reduce((acc, player) => {
            acc[player.id] = player;
            return acc;
          }, {})
        });
      }
    });

    socket.on('player_left', (data) => {
      console.log('PLAYER_LEFT:', data);
      if (currentRoom && data.updatedPlayers) {
        setCurrentRoom({
          ...currentRoom,
          players: data.updatedPlayers.reduce((acc, player) => {
            acc[player.id] = player;
            return acc;
          }, {}),
          hostId: data.newHostId || currentRoom.hostId
        });
      }
    });

    socket.on('host_migrated', (data) => {
      console.log('HOST_MIGRATED:', data);
      setError(`HOST TRANSFER: ${data.newHostNickname}`);
      setTimeout(() => setError(''), 3000);
    });

    socket.on('countdown_start', (data) => {
      console.log('COUNTDOWN_START:', data);
      setSentences(data.sentences);
      setCountdown(3);
      setView('COUNTDOWN');
      
      let count = 3;
      const interval = setInterval(() => {
        count--;
        setCountdown(count);
        if (count === 0) {
          clearInterval(interval);
        }
      }, 1000);
    });

    socket.on('game_start', (data) => {
      console.log('GAME_START:', data);
      setView('GAME');
      setCountdown(null);
    });

    socket.on('replay_started', (data) => {
      console.log('REPLAY INITIATED - Resetting all client state');
      console.log('  → Updated room with reset players:', data.room.players);
      
      setCurrentRoom(data.room);
      setGameEndData(null);
      setUserRole('PLAYER');
      setSentences([]);
      setCountdown(null);
      setView('LOBBY');
    });

    socket.on('sync_sentences', (data) => {
      console.log(`Syncing ${data.sentences.length} sentences for spectator`);
      setSentences(data.sentences);
    });

    socket.on('game_force_reset', (data) => {
      console.log('GAME FORCE RESET BY HOST - Resetting all client state');
      console.log('  → Updated room with reset players:', data.room.players);
      
      setCurrentRoom(data.room);
      setGameEndData(null);
      setUserRole('PLAYER');
      setSentences([]);
      setCountdown(null);
      setView('LOBBY');
    });

    return () => {
      socket.off('connect');
      socket.off('disconnect');
      socket.off('settings_updated');
      socket.off('player_joined');
      socket.off('player_left');
      socket.off('host_migrated');
      socket.off('countdown_start');
      socket.off('game_start');
      socket.off('replay_started');
      socket.off('sync_sentences');
      socket.off('game_force_reset');
    };
  }, [currentRoom]);

  useEffect(() => {
    const savedSession = localStorage.getItem('type_or_die_session');
    
    if (savedSession && connected && view === 'MENU') {
      const { playerId, roomCode } = JSON.parse(savedSession);
      
      console.log('Attempting reconnection...', { playerId, roomCode });
      setLoading(true);
      
      socket.emit('reconnect_attempt', { roomCode, playerId }, (response) => {
        if (response.success) {
          console.log('RECONNECTION SUCCESSFUL');
          setCurrentRoom(response.room);
          setPlayerId(response.playerId);
          
          const player = response.room.players[response.playerId];
          const isSpectator = response.room.spectators?.includes(response.playerId) || 
                              player?.status === 'DEAD';
          setUserRole(isSpectator ? 'SPECTATOR' : 'PLAYER');
          
          if (response.room.status === 'PLAYING' || response.room.status === 'COUNTDOWN') {
            setView('GAME');
          } else {
            setView('LOBBY');
          }
          
          setError('Reconnected successfully!');
          setTimeout(() => setError(''), 2000);
        } else {
          console.log('RECONNECTION FAILED:', response.error);
          setError(`RECONNECTION FAILED: ${response.error}`);
          localStorage.removeItem('type_or_die_session');
          setTimeout(() => setError(''), 3000);
        }
        setLoading(false);
      });
    }
  }, [connected, view]);

  useEffect(() => {
    const handlePlayerDied = (data) => {
      if (data.playerId === playerId) {
        console.log('💀 YOU DIED - Transitioning to spectator mode');
        setUserRole('SPECTATOR');
      }
    };

    socket.on('player_died', handlePlayerDied);

    return () => {
      socket.off('player_died', handlePlayerDied);
    };
  }, [playerId]);

  const handleCreateRoom = () => {
    if (!nickname.trim()) {
      setError('ERROR: NICKNAME REQUIRED');
      return;
    }

    setLoading(true);
    setError('');

    socket.emit('create_room', {
      nickname: nickname.trim(),
      settings: {
        sentenceCount: sentenceCount
      }
    }, (response) => {
      setLoading(false);
      
      if (response.success) {
        console.log('ROOM_CREATED:', response.roomCode);
        setCurrentRoom(response.room);
        setPlayerId(response.playerId);
        setUserRole('PLAYER');
        setView('LOBBY');
        localStorage.setItem('type_or_die_session', JSON.stringify({
          playerId: response.playerId,
          roomCode: response.room.roomCode
        }));
      } else {
        setError(`ERROR: ${response.error.toUpperCase()}`);
      }
    });
  };

  const handleJoinRoom = () => {
    if (!nickname.trim()) {
      setError('ERROR: NICKNAME REQUIRED');
      return;
    }

    if (!roomCode.trim() || roomCode.length !== 6) {
      setError('ERROR: INVALID ROOM CODE');
      return;
    }

    setLoading(true);
    setError('');

    socket.emit('join_room', {
      roomCode: roomCode.toUpperCase(),
      nickname: nickname.trim()
    }, (response) => {
      setLoading(false);
      
      if (response.success) {
        console.log('ROOM_JOINED:', response.room.roomCode);
        setCurrentRoom(response.room);
        setPlayerId(response.playerId);
        setUserRole(response.role);

        if (response.sentences && response.sentences.length > 0) {
          setSentences(response.sentences);
          console.log(`Loaded ${response.sentences.length} sentences for spectator`);
        }

        if (response.role === 'SPECTATOR') {
          setView('GAME');
        } else {
          setView('LOBBY');
        }

        localStorage.setItem('type_or_die_session', JSON.stringify({
          playerId: response.playerId,
          roomCode: response.room.roomCode
        }));
      } else {
        setError(`ERROR: ${response.error.toUpperCase()}`);
      }
    });
  };

  const handleLeaveRoom = () => {
    if (currentRoom) {
      socket.emit('leave_room', { roomCode: currentRoom.roomCode });
      localStorage.removeItem('type_or_die_session');
      setCurrentRoom(null);
      setPlayerId(null);
      setSentences([]);
      setGameEndData(null);
      setCountdown(null);
      setUserRole(null);
      setView('MENU');
      setRoomCode('');
    }
  };

  const handleChangeSentences = (value) => {
    if (currentRoom && currentRoom.hostId === playerId) {
      setCurrentRoom({
        ...currentRoom,
        settings: {
          ...currentRoom.settings,
          sentenceCount: value
        }
      });

      socket.emit('change_settings', {
        roomCode: currentRoom.roomCode,
        sentenceCount: value
      }, (response) => {
        if (!response.success) {
          setError(`ERROR: ${response.error.toUpperCase()}`);
        }
      });
    }
  };

  const copyRoomCode = () => {
    if (currentRoom) {
      navigator.clipboard.writeText(currentRoom.roomCode);
      setError('ROOM CODE COPIED TO CLIPBOARD');
      setTimeout(() => setError(''), 2000);
    }
  };

  const handleStartGame = () => {
    if (currentRoom && currentRoom.hostId === playerId) {
      setLoading(true);
      socket.emit('start_game', { roomCode: currentRoom.roomCode }, (response) => {
        setLoading(false);
        if (!response.success) {
          setError(`ERROR: ${response.error.toUpperCase()}`);
        }
      });
    }
  };

  if (view === 'MENU') {
    return (
      <div className="app">
        <div className="container">
          <header>
            <h1>Type or Die</h1>
            <p className="tagline">TYPE OR DIE</p>
          </header>

          <div className="status">
            {connected ? '[ONLINE]' : '[CONNECTING...]'}
          </div>

          {error && <div className="error">{error}</div>}

          <div className="form-section">
            <label>OPERATOR NAME</label>
            <input
              type="text"
              placeholder="ENTER CALLSIGN"
              value={nickname}
              onChange={(e) => setNickname(e.target.value.toUpperCase())}
              maxLength={20}
              className="input"
            />
          </div>

          <div className="form-section">
            <label>SENTENCE COUNT: {sentenceCount}</label>
            <input
              type="range"
              min="5"
              max="100"
              step="5"
              value={sentenceCount}
              onChange={(e) => setSentenceCount(parseInt(e.target.value))}
              className="slider"
            />
            <div className="slider-labels">
              <span>5</span>
              <span>100</span>
            </div>
          </div>

          <button 
            onClick={handleCreateRoom} 
            disabled={!connected || loading}
            className="btn-primary"
          >
            {loading ? 'INITIALIZING...' : 'CREATE ROOM'}
          </button>

          <div className="divider">OR</div>

          <div className="form-section">
            <label>ROOM ACCESS CODE</label>
            <input
              type="text"
              placeholder="XXXXXX"
              value={roomCode}
              onChange={(e) => setRoomCode(e.target.value.toUpperCase())}
              maxLength={6}
              className="input"
            />
          </div>

          <button 
            onClick={handleJoinRoom} 
            disabled={!connected || loading}
            className="btn-secondary"
          >
            {loading ? 'CONNECTING...' : 'JOIN ROOM'}
          </button>
        </div>
      </div>
    );
  }

  if (view === 'LOBBY' && currentRoom) {
    const isHost = currentRoom.hostId === playerId;
    const players = Object.values(currentRoom.players);

    console.log('  LOBBY VIEW DEBUG:');
    console.log('  Current room players:', currentRoom.players);
    console.log('  My player ID:', playerId);
    console.log('  My player status:', currentRoom.players[playerId]?.status);

    return (
      <div className="app">
        <div className="container">
          <div className="lobby-header">
            <button onClick={handleLeaveRoom} className="btn-back">
              EXIT
            </button>
            <div className="room-code-display">
              ROOM: <strong>{currentRoom.roomCode}</strong>
              <button onClick={copyRoomCode} className="btn-copy">
                COPY
              </button>
            </div>
          </div>

          {error && <div className="error">{error}</div>}

          <div className="settings-section">
            <h2>PARAMETERS</h2>
            <div className="form-section">
              <label>SENTENCE COUNT: {currentRoom.settings?.sentenceCount ?? 50}</label>
              <input
                type="range"
                min="5"
                max="100"
                step="5"
                value={currentRoom.settings?.sentenceCount ?? 50}
                onChange={(e) => handleChangeSentences(parseInt(e.target.value))}
                disabled={!isHost}
                className="slider"
              />
              <div className="slider-labels">
                <span>5</span>
                <span>100</span>
              </div>
              {!isHost && <p className="note">[HOST ONLY]</p>}
            </div>
          </div>

          <div className="players-section">
            <h2>OPERATORS ({players.length})</h2>
            <div className="player-list">
              {players.map((player) => (
                <div key={player.id} className="player-item">
                  {player.id === currentRoom.hostId && '[HOST] '}
                  {player.nickname}
                  {player.status === 'DEAD' && ' [DEAD - BUG]'}
                </div>
              ))}
            </div>
          </div>

          {isHost && (
            <button 
              onClick={handleStartGame}
              disabled={loading}
              className="btn-primary" 
              style={{ marginTop: '20px' }}
            >
              {loading ? 'INITIALIZING...' : 'BEGIN PROTOCOL'}
            </button>
          )}

          {!isHost && (
            <p className="note">AWAITING HOST AUTHORIZATION...</p>
          )}
        </div>
      </div>
    );
  }

  if (view === 'COUNTDOWN') {
    return (
      <div className="app">
        <div className="container countdown-container">
          <div className="countdown-number">
            {countdown > 0 ? countdown : 'GO!'}
          </div>
          <p className="countdown-text">
            {countdown > 0 ? 'GET READY TO TYPE...' : 'START TYPING NOW!'}
          </p>
        </div>
      </div>
    );
  }

  if (view === 'GAME' && currentRoom) {
    console.log('  GAME VIEW DEBUG:');
    console.log('  Current room players:', currentRoom.players);
    console.log('  My player ID:', playerId);
    console.log('  My player status:', currentRoom.players[playerId]?.status);
    console.log('  User role:', userRole);

    return (
      <GameScreen
        key={`game-${currentRoom.roomCode}-${currentRoom.gameStartedAt || 'lobby'}`}
        socket={socket}
        room={currentRoom}
        playerId={playerId}
        sentences={sentences}
        onLeave={handleLeaveRoom}
        isSpectator={userRole === 'SPECTATOR'}
      />
    );
  }

  if (view === 'FINISHED' && gameEndData) {
    console.log('Rendering GameEndScreen with:', {
      gameEndData,
      currentRoom,
      playerId
    });
    
    return (
      <GameEndScreen
        gameEndData={gameEndData}
        room={currentRoom}
        playerId={playerId}
        sentences={sentences}
        onMainMenu={() => {
          localStorage.removeItem('type_or_die_session');
          setSentences([]);
          setGameEndData(null);
          setCountdown(null);
          setUserRole(null);
          setView('MENU');
        }}
        onReplay={() => {
          console.log('REPLAY BUTTON CLICKED - Requesting replay from server');
          socket.emit('request_replay', { roomCode: currentRoom.roomCode }, (response) => {
            if (response.success) {
              console.log('Replay request successful');
            } else {
              console.error('Replay request failed:', response.error);
              setError(`ERROR: ${response.error.toUpperCase()}`);
            }
          });
        }}
      />
    );
  }

  return <div className="app">LOADING...</div>;
}

export default App;

// client/src/App.vue
<template>
  <div class="app" v-if="view === 'MENU'">
    <div class="container">
      <header>
        <h1>Type or Die</h1>
        <p class="tagline">TYPE OR DIE</p>
      </header>

      <div class="status">
        {{ connected ? '[ONLINE]' : '[CONNECTING...]' }}
      </div>

      <div v-if="error" class="error">{{ error }}</div>

      <div class="form-section">
        <label>OPERATOR NAME</label>
        <input
          type="text"
          placeholder="ENTER CALLSIGN"
          v-model="nickname"
          @input="nickname = nickname.toUpperCase()"
          :maxlength="20"
          class="input"
        />
      </div>

      <div class="form-section">
        <label>SENTENCE COUNT: {{ sentenceCount }}</label>
        <input
          type="range"
          min="5"
          max="100"
          step="5"
          v-model.number="sentenceCount"
          class="slider"
        />
        <div class="slider-labels">
          <span>5</span>
          <span>100</span>
        </div>
      </div>

      <button 
        @click="handleCreateRoom" 
        :disabled="!connected || loading"
        class="btn-primary"
      >
        {{ loading ? 'INITIALIZING...' : 'CREATE ROOM' }}
      </button>

      <div class="divider">OR</div>

      <div class="form-section">
        <label>ROOM ACCESS CODE</label>
        <input
          type="text"
          placeholder="XXXXXX"
          v-model="roomCode"
          @input="roomCode = roomCode.toUpperCase()"
          :maxlength="6"
          class="input"
        />
      </div>

      <button 
        @click="handleJoinRoom" 
        :disabled="!connected || loading"
        class="btn-secondary"
      >
        {{ loading ? 'CONNECTING...' : 'JOIN ROOM' }}
      </button>
    </div>
  </div>

  <div class="app" v-else-if="view === 'LOBBY' && currentRoom">
    <div class="container">
      <div class="lobby-header">
        <button @click="handleLeaveRoom" class="btn-back">
          EXIT
        </button>
        <div class="room-code-display">
          ROOM: <strong>{{ currentRoom.roomCode }}</strong>
          <button @click="copyRoomCode" class="btn-copy">
            COPY
          </button>
        </div>
      </div>

      <div v-if="error" class="error">{{ error }}</div>

      <div class="settings-section">
        <h2>PARAMETERS</h2>
        <div class="form-section">
          <label>SENTENCE COUNT: {{ currentRoom.settings?.sentenceCount ?? 50 }}</label>
          <input
            type="range"
            min="5"
            max="100"
            step="5"
            :value="currentRoom.settings?.sentenceCount ?? 50"
            @input="handleChangeSentences(parseInt($event.target.value))"
            :disabled="!isHost"
            class="slider"
          />
          <div class="slider-labels">
            <span>5</span>
            <span>100</span>
          </div>
          <p v-if="!isHost" class="note">[HOST ONLY]</p>
        </div>
      </div>

      <div class="players-section">
        <h2>OPERATORS ({{ players.length }})</h2>
        <div class="player-list">
          <div 
            v-for="player in players" 
            :key="player.id" 
            class="player-item"
          >
            {{ player.id === currentRoom.hostId ? '[HOST] ' : '' }}
            {{ player.nickname }}
            {{ player.status === 'DEAD' ? ' [DEAD - BUG]' : '' }}
          </div>
        </div>
      </div>

      <button 
        v-if="isHost"
        @click="handleStartGame"
        :disabled="loading"
        class="btn-primary" 
        style="margin-top: 20px"
      >
        {{ loading ? 'INITIALIZING...' : 'BEGIN PROTOCOL' }}
      </button>

      <p v-else class="note">AWAITING HOST AUTHORIZATION...</p>
    </div>
  </div>

  <div class="app" v-else-if="view === 'COUNTDOWN'">
    <div class="container countdown-container">
      <div class="countdown-number">
        {{ countdown > 0 ? countdown : 'GO!' }}
      </div>
      <p class="countdown-text">
        {{ countdown > 0 ? 'GET READY TO TYPE...' : 'START TYPING NOW!' }}
      </p>
    </div>
  </div>

  <GameScreen
    v-else-if="view === 'GAME' && currentRoom"
    :key="`game-${currentRoom.roomCode}-${currentRoom.gameStartedAt || 'lobby'}`"
    :socket="socket"
    :room="currentRoom"
    :player-id="playerId"
    :sentences="sentences"
    :is-spectator="userRole === 'SPECTATOR'"
    @leave="handleLeaveRoom"
  />

  <GameEndScreen
    v-else-if="view === 'FINISHED' && gameEndData"
    :game-end-data="gameEndData"
    :room="currentRoom"
    :player-id="playerId"
    :sentences="sentences"
    @main-menu="handleMainMenu"
    @replay="handleReplay"
  />

  <div v-else class="app">LOADING...</div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { io } from 'socket.io-client'
import GameScreen from './components/GameScreen.vue'
import GameEndScreen from './components/GameEndScreen.vue'

const socket = io()

// State
const connected = ref(false)
const view = ref('MENU')
const nickname = ref('')
const roomCode = ref('')
const currentRoom = ref(null)
const playerId = ref(null)
const sentenceCount = ref(15)
const error = ref('')
const loading = ref(false)
const countdown = ref(null)
const sentences = ref([])
const gameEndData = ref(null)
const userRole = ref(null)

// Computed
const isHost = computed(() => 
  currentRoom.value && currentRoom.value.hostId === playerId.value
)

const players = computed(() => 
  currentRoom.value ? Object.values(currentRoom.value.players) : []
)

// Socket event handlers
function setupSocketListeners() {
  socket.on('connect', () => {
    console.log('CONNECTION ESTABLISHED')
    connected.value = true
  })

  socket.on('disconnect', () => {
    console.log('CONNECTION TERMINATED')
    connected.value = false
  })

  socket.on('settings_updated', (data) => {
    console.log('SETTINGS_UPDATED:', data)
    if (currentRoom.value) {
      currentRoom.value = {
        ...currentRoom.value,
        settings: {
          ...currentRoom.value.settings,
          sentenceCount: data.sentenceCount
        }
      }
    }
  })

  socket.on('player_joined', (data) => {
    console.log('PLAYER_JOINED:', data)
    if (currentRoom.value && data.updatedPlayers) {
      currentRoom.value = {
        ...currentRoom.value,
        players: data.updatedPlayers.reduce((acc, player) => {
          acc[player.id] = player
          return acc
        }, {})
      }
    }
  })

  socket.on('player_left', (data) => {
    console.log('PLAYER_LEFT:', data)
    if (currentRoom.value && data.updatedPlayers) {
      currentRoom.value = {
        ...currentRoom.value,
        players: data.updatedPlayers.reduce((acc, player) => {
          acc[player.id] = player
          return acc
        }, {}),
        hostId: data.newHostId || currentRoom.value.hostId
      }
    }
  })

  socket.on('host_migrated', (data) => {
    console.log('HOST_MIGRATED:', data)
    error.value = `HOST TRANSFER: ${data.newHostNickname}`
    setTimeout(() => { error.value = '' }, 3000)
  })

  socket.on('countdown_start', (data) => {
    console.log('COUNTDOWN_START:', data)
    sentences.value = data.sentences
    countdown.value = 3
    view.value = 'COUNTDOWN'
    
    let count = 3
    const interval = setInterval(() => {
      count--
      countdown.value = count
      if (count === 0) {
        clearInterval(interval)
      }
    }, 1000)
  })

  socket.on('game_start', (data) => {
    console.log('GAME_START:', data)
    view.value = 'GAME'
    countdown.value = null
  })

  socket.on('replay_started', (data) => {
    console.log('REPLAY INITIATED - Resetting all client state')
    console.log('  → Updated room with reset players:', data.room.players)
    
    currentRoom.value = data.room
    gameEndData.value = null
    userRole.value = 'PLAYER'
    sentences.value = []
    countdown.value = null
    view.value = 'LOBBY'
  })

  socket.on('sync_sentences', (data) => {
    console.log(`Syncing ${data.sentences.length} sentences for spectator`)
    sentences.value = data.sentences
  })

  socket.on('game_force_reset', (data) => {
    console.log('GAME FORCE RESET BY HOST - Resetting all client state')
    console.log('  → Updated room with reset players:', data.room.players)
    
    currentRoom.value = data.room
    gameEndData.value = null
    userRole.value = 'PLAYER'
    sentences.value = []
    countdown.value = null
    view.value = 'LOBBY'
  })

  socket.on('game_ended', (data) => {
    console.log('App.vue received game_ended:', data)
    
    if (currentRoom.value) {
      currentRoom.value = {
        ...currentRoom.value,
        players: data.finalStats,
        status: 'FINISHED'
      }
    }
    
    gameEndData.value = data
    
    setTimeout(() => {
      view.value = 'FINISHED'
    }, 6200)
  })

  socket.on('player_died', (data) => {
    if (data.playerId === playerId.value) {
      console.log('💀 YOU DIED - Transitioning to spectator mode')
      userRole.value = 'SPECTATOR'
    }
  })
}

function cleanupSocketListeners() {
  socket.off('connect')
  socket.off('disconnect')
  socket.off('settings_updated')
  socket.off('player_joined')
  socket.off('player_left')
  socket.off('host_migrated')
  socket.off('countdown_start')
  socket.off('game_start')
  socket.off('replay_started')
  socket.off('sync_sentences')
  socket.off('game_force_reset')
  socket.off('game_ended')
  socket.off('player_died')
}

// Reconnection logic
watch([connected, view], () => {
  const savedSession = localStorage.getItem('type_or_die_session')
  
  if (savedSession && connected.value && view.value === 'MENU') {
    const session = JSON.parse(savedSession)
    
    console.log('Attempting reconnection...', session)
    loading.value = true
    
    socket.emit('reconnect_attempt', { 
      roomCode: session.roomCode, 
      playerId: session.playerId 
    }, (response) => {
      if (response.success) {
        console.log('RECONNECTION SUCCESSFUL')
        currentRoom.value = response.room
        playerId.value = response.playerId
        
        const player = response.room.players[response.playerId]
        const isSpectator = response.room.spectators?.includes(response.playerId) || 
                            player?.status === 'DEAD'
        userRole.value = isSpectator ? 'SPECTATOR' : 'PLAYER'
        
        if (response.room.status === 'PLAYING' || response.room.status === 'COUNTDOWN') {
          view.value = 'GAME'
        } else {
          view.value = 'LOBBY'
        }
        
        error.value = 'Reconnected successfully!'
        setTimeout(() => { error.value = '' }, 2000)
      } else {
        console.log('RECONNECTION FAILED:', response.error)
        error.value = `RECONNECTION FAILED: ${response.error}`
        localStorage.removeItem('type_or_die_session')
        setTimeout(() => { error.value = '' }, 3000)
      }
      loading.value = false
    })
  }
})

// Action handlers
function handleCreateRoom() {
  if (!nickname.value.trim()) {
    error.value = 'ERROR: NICKNAME REQUIRED'
    return
  }

  loading.value = true
  error.value = ''

  socket.emit('create_room', {
    nickname: nickname.value.trim(),
    settings: {
      sentenceCount: sentenceCount.value
    }
  }, (response) => {
    loading.value = false
    
    if (response.success) {
      console.log('ROOM_CREATED:', response.roomCode)
      currentRoom.value = response.room
      playerId.value = response.playerId
      userRole.value = 'PLAYER'
      view.value = 'LOBBY'
      localStorage.setItem('type_or_die_session', JSON.stringify({
        playerId: response.playerId,
        roomCode: response.room.roomCode
      }))
    } else {
      error.value = `ERROR: ${response.error.toUpperCase()}`
    }
  })
}

function handleJoinRoom() {
  if (!nickname.value.trim()) {
    error.value = 'ERROR: NICKNAME REQUIRED'
    return
  }

  if (!roomCode.value.trim() || roomCode.value.length !== 6) {
    error.value = 'ERROR: INVALID ROOM CODE'
    return
  }

  loading.value = true
  error.value = ''

  socket.emit('join_room', {
    roomCode: roomCode.value.toUpperCase(),
    nickname: nickname.value.trim()
  }, (response) => {
    loading.value = false
    
    if (response.success) {
      console.log('ROOM_JOINED:', response.room.roomCode)
      currentRoom.value = response.room
      playerId.value = response.playerId
      userRole.value = response.role

      if (response.sentences && response.sentences.length > 0) {
        sentences.value = response.sentences
        console.log(`Loaded ${response.sentences.length} sentences for spectator`)
      }

      if (response.role === 'SPECTATOR') {
        view.value = 'GAME'
      } else {
        view.value = 'LOBBY'
      }

      localStorage.setItem('type_or_die_session', JSON.stringify({
        playerId: response.playerId,
        roomCode: response.room.roomCode
      }))
    } else {
      error.value = `ERROR: ${response.error.toUpperCase()}`
    }
  })
}

function handleLeaveRoom() {
  if (currentRoom.value) {
    socket.emit('leave_room', { roomCode: currentRoom.value.roomCode })
    localStorage.removeItem('type_or_die_session')
    currentRoom.value = null
    playerId.value = null
    sentences.value = []
    gameEndData.value = null
    countdown.value = null
    userRole.value = null
    view.value = 'MENU'
    roomCode.value = ''
  }
}

function handleChangeSentences(value) {
  if (currentRoom.value && currentRoom.value.hostId === playerId.value) {
    currentRoom.value = {
      ...currentRoom.value,
      settings: {
        ...currentRoom.value.settings,
        sentenceCount: value
      }
    }

    socket.emit('change_settings', {
      roomCode: currentRoom.value.roomCode,
      sentenceCount: value
    }, (response) => {
      if (!response.success) {
        error.value = `ERROR: ${response.error.toUpperCase()}`
      }
    })
  }
}

function copyRoomCode() {
  if (currentRoom.value) {
    navigator.clipboard.writeText(currentRoom.value.roomCode)
    error.value = 'ROOM CODE COPIED TO CLIPBOARD'
    setTimeout(() => { error.value = '' }, 2000)
  }
}

function handleStartGame() {
  if (currentRoom.value && currentRoom.value.hostId === playerId.value) {
    loading.value = true
    socket.emit('start_game', { roomCode: currentRoom.value.roomCode }, (response) => {
      loading.value = false
      if (!response.success) {
        error.value = `ERROR: ${response.error.toUpperCase()}`
      }
    })
  }
}

function handleMainMenu() {
  localStorage.removeItem('type_or_die_session')
  sentences.value = []
  gameEndData.value = null
  countdown.value = null
  userRole.value = null
  view.value = 'MENU'
}

function handleReplay() {
  console.log('REPLAY BUTTON CLICKED - Requesting replay from server')
  socket.emit('request_replay', { roomCode: currentRoom.value.roomCode }, (response) => {
    if (response.success) {
      console.log('Replay request successful')
    } else {
      console.error('Replay request failed:', response.error)
      error.value = `ERROR: ${response.error.toUpperCase()}`
    }
  })
}

// Lifecycle
onMounted(() => {
  setupSocketListeners()
})

onUnmounted(() => {
  cleanupSocketListeners()
})
</script>

<style>
@import './App.css';
</style>
