// client/src/components/game/LeaderboardPanel.vue
<template>
  <div class="leaderboard-zone">
    <div class="lb-header">LIVE LEADERBOARD</div>
    <div class="lb-list">
      <div
        v-for="(player, idx) in sortedPlayers"
        :key="player.id"
        :class="[
          'lb-entry',
          { 'lb-dead': player.status === 'DEAD' },
          { 'lb-you': player.id === (highlightedPlayerId || playerId) },
          { 'lb-clickable': onPlayerClick && player.status === 'ALIVE' }
        ]"
        @click="handlePlayerClick(player)"
        :style="{ cursor: onPlayerClick && player.status === 'ALIVE' ? 'pointer' : 'default' }"
      >
        <div class="lb-rank">
          {{ idx + 1 }}. {{ player.nickname }}
          {{ player.status === 'DEAD' ? ' [X]' : '' }}
        </div>
        <div class="lb-bar">
          <div 
            class="lb-fill" 
            :style="{ width: `${(player.completedSentences / totalSentences) * 100}%` }"
          />
        </div>
        <div class="lb-stats">
          <span>{{ player.completedSentences }}/{{ totalSentences }}</span>
          <span>{{ player.status === 'ALIVE' ? `1/${player.rouletteOdds}` : '--' }}</span>
          <span>WPM {{ player.averageWPM || 0 }}</span>
        </div>
      </div>
    </div>

    <div class="stats-panel">
      <div class="stats-header">YOUR DATA</div>
      <div class="stats-line">
        ACC: {{ currentPlayer.totalTypedChars > 0 
          ? ((currentPlayer.totalCorrectChars / currentPlayer.totalTypedChars) * 100).toFixed(1) 
          : 100 }}%
      </div>
      <div class="stats-line">HIT: {{ currentPlayer.totalCorrectChars || 0 }}</div>
      <div class="stats-line">ERR: {{ currentPlayer.totalMistypes || 0 }}</div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  players: {
    type: Object,
    required: true
  },
  playerId: {
    type: String,
    required: true
  },
  totalSentences: {
    type: Number,
    required: true
  },
  onPlayerClick: {
    type: Function,
    default: undefined
  },
  highlightedPlayerId: {
    type: String,
    default: null
  }
})

const sortedPlayers = computed(() => {
  return Object.values(props.players).sort((a, b) => {
    if (a.status === 'ALIVE' && b.status !== 'ALIVE') return -1
    if (a.status !== 'ALIVE' && b.status === 'ALIVE') return 1
    if (b.completedSentences !== a.completedSentences) {
      return b.completedSentences - a.completedSentences
    }
    return b.totalCorrectChars - a.totalCorrectChars
  })
})

const currentPlayer = computed(() => 
  props.players[props.playerId] || {}
)

function handlePlayerClick(player) {
  if (props.onPlayerClick && player.status === 'ALIVE') {
    props.onPlayerClick(player.id)
  }
}
</script>

// client/src/components/game/LeaderboardPanel.jsx
import React from 'react';

function LeaderboardPanel({ players, playerId, totalSentences, onPlayerClick, highlightedPlayerId }) {
  const sortedPlayers = Object.values(players).sort((a, b) => {
    if (a.status === 'ALIVE' && b.status !== 'ALIVE') return -1;
    if (a.status !== 'ALIVE' && b.status === 'ALIVE') return 1;
    if (b.completedSentences !== a.completedSentences) {
      return b.completedSentences - a.completedSentences;
    }
    return b.totalCorrectChars - a.totalCorrectChars;
  });

  const currentPlayer = players[playerId] || {};

  return (
    <div className="leaderboard-zone">
      <div className="lb-header">LIVE LEADERBOARD</div>
      <div className="lb-list">
        {sortedPlayers.map((player, idx) => (
          <div
            key={player.id}
            className={`lb-entry ${player.status === 'DEAD' ? 'lb-dead' : ''} ${player.id === (highlightedPlayerId || playerId) ? 'lb-you' : ''} ${onPlayerClick ? 'lb-clickable' : ''}`}
            onClick={() => onPlayerClick && player.status === 'ALIVE' && onPlayerClick(player.id)}
            style={{ cursor: onPlayerClick && player.status === 'ALIVE' ? 'pointer' : 'default' }}
          >
            <div className="lb-rank">
              {idx + 1}. {player.nickname}
              {player.status === 'DEAD' && ' [X]'}
            </div>
            <div className="lb-bar">
              <div 
                className="lb-fill" 
                style={{ width: `${(player.completedSentences / totalSentences) * 100}%` }}
              />
            </div>
            <div className="lb-stats">
              <span>{player.completedSentences}/{totalSentences}</span>
              <span>{player.status === 'ALIVE' ? `1/${player.rouletteOdds}` : '--'}</span>
              <span>WPM {player.averageWPM || 0}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="stats-panel">
        <div className="stats-header">YOUR DATA</div>
        <div className="stats-line">
          ACC: {currentPlayer.totalTypedChars > 0 
            ? ((currentPlayer.totalCorrectChars / currentPlayer.totalTypedChars) * 100).toFixed(1) 
            : 100}%
        </div>
        <div className="stats-line">HIT: {currentPlayer.totalCorrectChars || 0}</div>
        <div className="stats-line">ERR: {currentPlayer.totalMistypes || 0}</div>
      </div>
    </div>
  );
}

export default LeaderboardPanel;
