// client/src/components/GameEndScreen.vue
<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  gameEndData: Object,
  room: Object,
  playerId: String,
  sentences: Array
})

const emit = defineEmits(['mainMenu', 'replay'])

const activeTab = ref('leaderboard')

// --- COMPUTED PROPERTIES ---

const isValidSession = computed(() => {
  return props.gameEndData && props.room && props.playerId
})

const winnerId = computed(() => props.gameEndData?.winnerId)
const finalStats = computed(() => props.gameEndData?.finalStats || {})
const currentPlayer = computed(() => finalStats.value[props.playerId] || {})

const totalSentences = computed(() => {
  return props.sentences?.length || props.room?.settings?.sentenceCount || 0
})

const grade = computed(() => {
  const p = currentPlayer.value
  
  if (!p || p.status === 'SPECTATOR') return '-'
  if (p.status === 'DEAD') return 'F'
  if (!p.totalTypedChars) return '-'

  const acc = p.totalCorrectChars / p.totalTypedChars

  if (acc === 1) return 'SS'
  if (acc > 0.98) return 'S'
  if (acc > 0.95) return 'A'
  if (acc > 0.90) return 'B'
  return 'C'
})

const accuracy = computed(() => {
  const p = currentPlayer.value
  return p.totalTypedChars > 0
    ? ((p.totalCorrectChars / p.totalTypedChars) * 100).toFixed(2)
    : "0.00"
})

const sortedPlayers = computed(() => {
  return Object.values(finalStats.value).sort((a, b) => {
    if (a.id === winnerId.value) return -1
    if (b.id === winnerId.value) return 1
    if (a.status === 'ALIVE' && b.status !== 'ALIVE') return -1
    if (a.status !== 'ALIVE' && b.status === 'ALIVE') return 1
    return b.completedSentences - a.completedSentences
  })
})

const rouletteHistoryReversed = computed(() => {
  const history = currentPlayer.value.rouletteHistory || []
  return [...history].reverse()
})

// --- ACTIONS ---

const onMainMenu = () => emit('mainMenu')
const onReplay = () => emit('replay')
</script>

<template>
  <div class="results-overlay">
    
    <div v-if="!isValidSession" class="terminal-results error-state">
      <div class="results-header">
        <span>FATAL ERROR</span>
        <span>DATA_CORRUPT</span>
      </div>
      <div class="error-body">
        <p>CRITICAL SYSTEM FAILURE</p>
        <p>SESSION LOST</p>
        <button @click="onMainMenu" class="results-btn primary">
          FORCE ABORT
        </button>
      </div>
    </div>

    <div v-else class="terminal-results">
      
      <div class="results-header">
        <span class="header-title">MISSION REPORT</span>
        <span class="header-id">ID: {{ room.roomCode }}</span>
      </div>

      <div class="results-grid">
        
        <div class="results-summary">
          <div class="grade-container">
            <span class="grade-label">ASSESSMENT</span>
            <span class="grade-value" :class="`grade-${grade}`">{{ grade }}</span>
          </div>

          <div class="stats-block">
            <div class="stat-row">
              <span class="stat-label">STATUS</span>
              <span 
                class="stat-value" 
                :class="currentPlayer.status === 'DEAD' ? 'status-dead' : 'status-alive'"
              >
                {{ currentPlayer.status || 'SPECTATOR' }}
              </span>
            </div>
            <div class="stat-row">
              <span class="stat-label">COMPLETION</span>
              <span class="stat-value">{{ currentPlayer.completedSentences || 0 }}/{{ totalSentences }}</span>
            </div>
            <div class="stat-row">
              <span class="stat-label">ACCURACY</span>
              <span class="stat-value">{{ accuracy }}%</span>
            </div>
            <div class="stat-row">
              <span class="stat-label">SPEED</span>
              <span class="stat-value">{{ currentPlayer.averageWPM || 0 }} WPM</span>
            </div>
            <div class="stat-row">
              <span class="stat-label">ERRORS</span>
              <span class="stat-value">{{ currentPlayer.totalMistypes || 0 }}</span>
            </div>
          </div>
        </div>

        <div class="results-data">
          <div class="tabs-nav">
            <button 
              class="tab-btn" 
              :class="{ active: activeTab === 'leaderboard' }"
              @click="activeTab = 'leaderboard'"
            >
              RANKING
            </button>
            <button 
              class="tab-btn" 
              :class="{ active: activeTab === 'sentences' }"
              @click="activeTab = 'sentences'"
            >
              LOGS
            </button>
            <button 
              class="tab-btn" 
              :class="{ active: activeTab === 'roulette' }"
              @click="activeTab = 'roulette'"
            >
              CASUALTY
            </button>
          </div>

          <div class="tab-viewport">
            
            <div v-if="activeTab === 'leaderboard'" class="data-list">
              <div 
                v-for="(p, i) in sortedPlayers" 
                :key="p.id" 
                class="data-row"
                :class="{ 
                  'is-self': p.id === playerId, 
                  'is-dead': p.status === 'DEAD' 
                }"
              >
                <span class="row-rank">{{ (i + 1).toString().padStart(2, '0') }}</span>
                <span class="row-name">
                  {{ p.nickname }}
                  <span v-if="p.id === winnerId" class="badge-win">[WINNER]</span>
                  <span v-if="p.status === 'DEAD'" class="badge-dead">[KIA]</span>
                </span>
                <span class="row-stat">{{ p.completedSentences }}/{{ totalSentences }}</span>
                <span class="row-stat">{{ p.averageWPM }} WPM</span>
              </div>
            </div>

            <div v-if="activeTab === 'sentences'" class="data-list">
              <div 
                v-for="(s, idx) in (currentPlayer.sentenceHistory || [])" 
                :key="idx" 
                class="data-row history-row"
              >
                <span class="row-index">{{ (s.sentenceIndex + 1).toString().padStart(2, '0') }}</span>
                <span class="row-content">
                  {{ s.completed ? 'COMPLETED' : `FAILED: ${s.deathReason}` }}
                </span>
                <span class="row-stat">{{ s.wpm || 0 }} WPM</span>
                <span class="row-stat">{{ s.timeUsed.toFixed(1) }}s</span>
              </div>
              <div v-if="!currentPlayer.sentenceHistory?.length" class="empty-state">
                NO_DATA_AVAILABLE
              </div>
            </div>

            <div v-if="activeTab === 'roulette'" class="data-list">
              <div 
                v-for="(r, i) in rouletteHistoryReversed" 
                :key="i" 
                class="data-row roulette-row"
                :class="r.survived ? 'survived' : 'fatal'"
              >
                <span class="row-odds">{{ r.odds }}</span>
                <span class="row-chamber">[{{ r.survived ? 'EMPTY' : 'BULLET' }}]</span>
                <span class="row-result">{{ r.survived ? 'SURVIVED' : 'FATAL' }}</span>
              </div>
              <div v-if="!currentPlayer.rouletteHistory?.length" class="empty-state">
                NO_CASUALTY_EVENTS
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="results-actions">
        <button class="results-btn" @click="onReplay">
          RETURN TO LOBBY
        </button>
        <button class="results-btn" @click="onMainMenu">
          EXIT TO MENU
        </button>
      </div>

    </div>
  </div>
</template>

<style scoped>
@import './GameEndScreen.css';
</style>

// client/src/components/GameEndScreen.jsx
import { useState } from 'react';
import './GameEndScreen.css';

function GameEndScreen({ gameEndData, room, playerId, sentences, onMainMenu, onReplay }) {
  const [activeTab, setActiveTab] = useState('leaderboard');

  if (!gameEndData || !room || !playerId) {
    return (
      <div className="results-overlay">
        <div className="terminal-results error-state">
          <div className="results-header">
            <span>FATAL ERROR</span>
            <span>DATA_CORRUPT</span>
          </div>
          <div className="error-body">
            <p>CRITICAL SYSTEM FAILURE</p>
            <p>SESSION LOST</p>
            <button onClick={onMainMenu} className="results-btn primary">
              FORCE ABORT
            </button>
          </div>
        </div>
      </div>
    );
  }

  const { winnerId, finalStats } = gameEndData;
  const currentPlayer = finalStats[playerId] || {};
  const totalSentences = sentences?.length || room.settings?.sentenceCount || 0;
  
  const calculateGrade = (player) => {
    if (!player || player.status === 'DEAD') return 'F';
    
    if (!player.totalTypedChars) return '-';
    
    const acc = player.totalCorrectChars / player.totalTypedChars;
    
    if (acc === 1) return 'SS';
    if (acc > 0.98) return 'S';
    if (acc > 0.95) return 'A';
    if (acc > 0.90) return 'B';
    return 'C';
  };

  const grade = calculateGrade(currentPlayer);
  
  const accuracy = currentPlayer.totalTypedChars > 0
    ? ((currentPlayer.totalCorrectChars / currentPlayer.totalTypedChars) * 100).toFixed(2)
    : "0.00";

  const sortedPlayers = Object.values(finalStats).sort((a, b) => {
    if (a.id === winnerId) return -1;
    if (b.id === winnerId) return 1;
    if (a.status === 'ALIVE' && b.status !== 'ALIVE') return -1;
    if (a.status !== 'ALIVE' && b.status === 'ALIVE') return 1;
    return b.completedSentences - a.completedSentences;
  });

  return (
    <div className="results-overlay">
      <div className="terminal-results">
        
        <div className="results-header">
          <span className="header-title">MISSION REPORT</span>
          <span className="header-id">ID: {room.roomCode}</span>
        </div>

        <div className="results-grid">
          
          <div className="results-summary">
            <div className="grade-container">
              <span className="grade-label">ASSESSMENT</span>
              <span className={`grade-value grade-${grade}`}>{grade}</span>
            </div>

            <div className="stats-block">
              <div className="stat-row">
                <span className="stat-label">STATUS</span>
                <span className={`stat-value ${currentPlayer.status === 'DEAD' ? 'status-dead' : 'status-alive'}`}>
                  {currentPlayer.status || 'SPECTATOR'}
                </span>
              </div>
              <div className="stat-row">
                <span className="stat-label">COMPLETION</span>
                <span className="stat-value">{currentPlayer.completedSentences || 0}/{totalSentences}</span>
              </div>
              <div className="stat-row">
                <span className="stat-label">ACCURACY</span>
                <span className="stat-value">{accuracy}%</span>
              </div>
              <div className="stat-row">
                <span className="stat-label">SPEED</span>
                <span className="stat-value">{currentPlayer.averageWPM || 0} WPM</span>
              </div>
              <div className="stat-row">
                <span className="stat-label">ERRORS</span>
                <span className="stat-value">{currentPlayer.totalMistypes || 0}</span>
              </div>
            </div>
          </div>

          <div className="results-data">
            <div className="tabs-nav">
              <button 
                className={`tab-btn ${activeTab === 'leaderboard' ? 'active' : ''}`}
                onClick={() => setActiveTab('leaderboard')}
              >
                RANKING
              </button>
              <button 
                className={`tab-btn ${activeTab === 'sentences' ? 'active' : ''}`}
                onClick={() => setActiveTab('sentences')}
              >
                LOGS
              </button>
              <button 
                className={`tab-btn ${activeTab === 'roulette' ? 'active' : ''}`}
                onClick={() => setActiveTab('roulette')}
              >
                CASUALTY
              </button>
            </div>

            <div className="tab-viewport">
              {activeTab === 'leaderboard' && (
                <div className="data-list">
                  {sortedPlayers.map((p, i) => (
                    <div 
                      key={p.id} 
                      className={`data-row ${p.id === playerId ? 'is-self' : ''} ${p.status === 'DEAD' ? 'is-dead' : ''}`}
                    >
                      <span className="row-rank">{(i + 1).toString().padStart(2, '0')}</span>
                      <span className="row-name">
                        {p.nickname}
                        {p.id === winnerId && <span className="badge-win">[WINNER]</span>}
                        {p.status === 'DEAD' && <span className="badge-dead">[KIA]</span>}
                      </span>
                      <span className="row-stat">{p.completedSentences}/{totalSentences}</span>
                      <span className="row-stat">{p.averageWPM} WPM</span>
                    </div>
                  ))}
                </div>
              )}

              {activeTab === 'sentences' && (
                <div className="data-list">
                  {(currentPlayer.sentenceHistory || []).map((s, idx) => (
                    <div key={idx} className="data-row history-row">
                      <span className="row-index">{(s.sentenceIndex + 1).toString().padStart(2, '0')}</span>
                      <span className="row-content">
                        {s.completed ? 'COMPLETED' : `FAILED: ${s.deathReason}`}
                      </span>
                      <span className="row-stat">{s.wpm || 0} WPM</span>
                      <span className="row-stat">{s.timeUsed.toFixed(1)}s</span>
                    </div>
                  ))}
                  {(!currentPlayer.sentenceHistory?.length) && (
                    <div className="empty-state">NO_DATA_AVAILABLE</div>
                  )}
                </div>
              )}

              {activeTab === 'roulette' && (
                <div className="data-list">
                  {[...(currentPlayer.rouletteHistory || [])].reverse().map((r, i) => (
                    <div key={i} className={`data-row roulette-row ${r.survived ? 'survived' : 'fatal'}`}>
                      <span className="row-odds">{r.odds}</span>
                      <span className="row-chamber">[{r.survived ? 'EMPTY' : 'BULLET'}]</span>
                      <span className="row-result">{r.survived ? 'SURVIVED' : 'FATAL'}</span>
                    </div>
                  ))}
                  {(!currentPlayer.rouletteHistory?.length) && (
                    <div className="empty-state">NO_CASUALTY_EVENTS</div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="results-actions">
          <button className="results-btn" onClick={onReplay}>
            RETURN TO LOBBY
          </button>
          <button className="results-btn" onClick={onMainMenu}>
            EXIT TO MENU
          </button>
        </div>

      </div>
    </div>
  );
}

export default GameEndScreen;
