// client/src/components/GameScreen.vue
<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import GameController from './game/GameController.js'
import StatusHUD from './game/StatusHUD.vue'
import TypingField from './game/TypingField.vue'
import LeaderboardPanel from './game/LeaderboardPanel.vue'
import RouletteRevolver from './RouletteRevolver.vue'

const props = defineProps({
  socket: { type: Object, required: true },
  room: { type: Object, required: true },
  playerId: { type: String, required: true },
  sentences: { type: Array, required: true },
  isSpectator: { type: Boolean, default: false }
})

const emit = defineEmits(['leave'])

const players = ref({})
const currentSentenceIndex = ref(0)
const currentWordIndex = ref(0)
const currentCharInWord = ref(0)
const remainingTime = ref(20)
const mistypeFlash = ref(false)
const flashKey = ref(0)
const isProcessingError = ref(false)
const spectatingPlayerId = ref(null)
const showRoulette = ref(false)
const isRouletteActive = ref(false)
const rouletteResult = ref(null)
const showVictory = ref(false)
const showAbortConfirm = ref(false)


const isHost = computed(() => props.room.hostId === props.playerId)

let timerInterval = null
let spectatorInterval = null

const initializePlayers = () => {
  const initialPlayers = {}
  Object.keys(props.room.players).forEach(pId => {
    initialPlayers[pId] = {
      ...props.room.players[pId],
      currentSentenceIndex: 0,
      currentWordIndex: 0,
      currentCharInWord: 0,
      currentCharIndex: 0,
      completedSentences: 0,
      totalCorrectChars: 0,
      totalTypedChars: 0,
      totalMistypes: 0,
      averageWPM: 0,
      mistakeStrikes: 0,
      status: 'ALIVE',
      sentenceStartTime: Date.now(),
      calculatedTime: 20
    }
  })
  players.value = initialPlayers
  
  if (props.isSpectator) {
    const alivePlayers = Object.values(initialPlayers).filter(p => p.status === 'ALIVE')
    if (alivePlayers.length > 0) {
      spectatingPlayerId.value = alivePlayers[0].id
    }
  }
}

initializePlayers()

const currentPlayer = computed(() => players.value[props.playerId] || {})
const status = computed(() => currentPlayer.value.status || 'ALIVE')

const spectatorTarget = computed(() => {
  if (!props.isSpectator || !spectatingPlayerId.value) return null
  return players.value[spectatingPlayerId.value] || null
})

const spectatorDisplayTime = computed(() => {
  if (!spectatorTarget.value) return 20
  return spectatorTarget.value.calculatedTime ?? 20
})

const currentSentence = computed(() => props.sentences[currentSentenceIndex.value] || '')
const words = computed(() => currentSentence.value.split(' '))
const currentWord = computed(() => words.value[currentWordIndex.value] || '')

const handleResetGame = () => {
  showAbortConfirm.value = true
}

const confirmAbort = () => {
  props.socket.emit('force_reset_game', { roomCode: props.room.roomCode }, (response) => {
    if (!response?.success) {
      console.error('Failed to abort game:', response?.error);
    }
  });
  showAbortConfirm.value = false;
}

const cancelAbort = () => {
  showAbortConfirm.value = false
}

const startMainTimer = () => {
  if (timerInterval) clearInterval(timerInterval)
  timerInterval = setInterval(() => {
    const prev = remainingTime.value
    const newTime = Math.max(0, prev - 0.1)
    remainingTime.value = newTime
    
    if (newTime <= 0 && prev > 0) {
      props.socket.emit('sentence_timeout', {
        roomCode: props.room.roomCode,
        sentenceIndex: currentSentenceIndex.value
      })
    }
  }, 100)
}

const startSpectatorTimer = () => {
  if (spectatorInterval) clearInterval(spectatorInterval)
  spectatorInterval = setInterval(() => {
    if (!spectatorTarget.value || !spectatorTarget.value.sentenceStartTime) return
    
    const elapsed = (Date.now() - spectatorTarget.value.sentenceStartTime) / 1000
    const calculated = Math.max(0, 20 - elapsed)
    
    if (players.value[spectatingPlayerId.value]) {
      players.value[spectatingPlayerId.value].calculatedTime = calculated
    }
  }, 100)
}

watch([status, currentSentenceIndex, () => props.isSpectator], () => {
  if (props.isSpectator) {
    if (timerInterval) clearInterval(timerInterval)
    return
  }
  
  if (status.value === 'ALIVE') {
    startMainTimer()
  } else {
    if (timerInterval) clearInterval(timerInterval)
  }
}, { immediate: true })

watch([() => props.isSpectator, spectatingPlayerId], () => {
  if (props.isSpectator && spectatingPlayerId.value) {
    startSpectatorTimer()
  } else {
    if (spectatorInterval) clearInterval(spectatorInterval)
  }
})

const handleKeyPress = (e) => {
  if (status.value !== 'ALIVE' || isProcessingError.value || props.isSpectator || isRouletteActive.value) return

  const key = e.key
  if (GameController.isNavigationKey(key) && key !== ' ') return
  e.preventDefault()

  const _words = words.value
  const _currentWord = currentWord.value
  const charIndex = GameController.calculateGlobalCharIndex(_words, currentWordIndex.value, currentCharInWord.value)

  if (key === ' ') {
    if (GameController.shouldAdvanceWord(currentCharInWord.value, _currentWord)) {
      if (currentWordIndex.value < _words.length - 1) {
        currentWordIndex.value++
        currentCharInWord.value = 0
        
        props.socket.emit('char_typed', {
          roomCode: props.room.roomCode,
          char: ' ',
          charIndex: charIndex,
          timestamp: Date.now()
        })
      }
    } else {
      triggerMistype(key, _currentWord[currentCharInWord.value], charIndex)
    }
    return
  }

  const expectedChar = _currentWord[currentCharInWord.value]
  if (GameController.validateChar(key, expectedChar)) {
    const newCharInWord = currentCharInWord.value + 1
    currentCharInWord.value = newCharInWord

    props.socket.emit('char_typed', {
      roomCode: props.room.roomCode,
      char: key,
      charIndex: charIndex,
      timestamp: Date.now()
    })

    if (GameController.shouldCompleteSentence(currentWordIndex.value, _words, newCharInWord, _currentWord)) {
      setTimeout(() => {
        const nextIndex = currentSentenceIndex.value + 1
        if (nextIndex < props.sentences.length) {
          currentSentenceIndex.value = nextIndex
          currentWordIndex.value = 0
          currentCharInWord.value = 0
        }
      }, 100)
    }
  } else {
    triggerMistype(key, expectedChar, charIndex)
  }
}

const triggerMistype = (typed, expected, charIndex) => {
  isProcessingError.value = true
  props.socket.emit('mistype', {
    roomCode: props.room.roomCode,
    expectedChar: expected,
    typedChar: typed,
    charIndex: charIndex,
    sentenceIndex: currentSentenceIndex.value
  })
  currentWordIndex.value = 0
  currentCharInWord.value = 0
}

const onPlayerProgress = (data) => {
  if (players.value[data.playerId]) {
    players.value[data.playerId] = {
      ...players.value[data.playerId],
      currentCharIndex: data.charIndex,
      currentSentenceIndex: data.sentenceIndex,
      currentWordIndex: data.currentWordIndex || 0,
      currentCharInWord: data.currentCharInWord || 0,
      completedSentences: data.completedSentences,
      totalCorrectChars: data.totalCorrectChars,
      totalTypedChars: data.totalTypedChars,
      totalMistypes: data.totalMistypes,
      averageWPM: data.wpm,
      status: data.status,
      sentenceStartTime: data.sentenceStartTime
    }
  }
}

const onPlayerStrike = (data) => {
  if (players.value[data.playerId]) {
    players.value[data.playerId] = {
      ...players.value[data.playerId],
      mistakeStrikes: data.strikes,
      sentenceStartTime: data.sentenceStartTime,
      currentWordIndex: data.currentWordIndex,
      currentCharInWord: data.currentCharInWord,
      currentCharIndex: data.currentCharIndex
    }
    
    // Logic specific to the current user (Visuals & Timer Reset)
    if (data.playerId === props.playerId) {
      remainingTime.value = 20
      mistypeFlash.value = true
      flashKey.value += 1
      
      setTimeout(() => {
        mistypeFlash.value = false
        isProcessingError.value = false
      }, 300)
    }
  }
}

const onRouletteResult = (data) => {
  if (data.playerId === props.playerId) {
    rouletteResult.value = data
    showRoulette.value = true
    isRouletteActive.value = true
    
    remainingTime.value = 20
    if (players.value[props.playerId]) {
      players.value[props.playerId].mistakeStrikes = 0
    }
    
    if (timerInterval) clearInterval(timerInterval)
    
    setTimeout(() => {
      showRoulette.value = false
      rouletteResult.value = null
      isRouletteActive.value = false
      
      if (players.value[props.playerId]?.status === 'ALIVE') {
        startMainTimer()
      }
    }, 5000)
  }
}

const onPlayerDied = (data) => {
  if (players.value[data.playerId]) {
    players.value[data.playerId] = {
      ...players.value[data.playerId],
      status: 'DEAD'
    }
  }
}

const onSentenceCompleted = (data) => {
  if (players.value[data.playerId]) {
    const p = players.value[data.playerId]
    p.completedSentences = (p.completedSentences || 0) + 1
    p.currentSentenceIndex = data.newSentenceIndex
    p.sentenceStartTime = data.sentenceStartTime
    p.currentWordIndex = 0
    p.currentCharInWord = 0
    p.currentCharIndex = 0
    
    players.value[data.playerId] = { ...p }
    
    if (data.playerId === props.playerId) {
      remainingTime.value = 20
    }
  }
}

const onGameEnded = (data) => {
  console.log('🏁 Game ended event received:', data)
  Object.keys(data.finalStats).forEach(pId => {
     if (players.value[pId]) {
       players.value[pId] = { ...players.value[pId], ...data.finalStats[pId] }
     }
  })

  if (data.winnerId === props.playerId && data.reason === 'COMPLETION') {
    showVictory.value = true
  }
}

// --- 2. MOUNT & UNMOUNT ---

onMounted(() => {
  document.addEventListener('keydown', handleKeyPress)

  // Attach the named functions
  props.socket.on('player_progress', onPlayerProgress)
  props.socket.on('player_strike', onPlayerStrike)
  props.socket.on('roulette_result', onRouletteResult)
  props.socket.on('player_died', onPlayerDied)
  props.socket.on('sentence_completed', onSentenceCompleted)
  props.socket.on('game_ended', onGameEnded)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyPress)
  if (timerInterval) clearInterval(timerInterval)
  if (spectatorInterval) clearInterval(spectatorInterval)
  
  // Detach ONLY these specific functions
  // This prevents wiping the global game_ended listener in App.vue
  props.socket.off('player_progress', onPlayerProgress)
  props.socket.off('player_strike', onPlayerStrike)
  props.socket.off('roulette_result', onRouletteResult)
  props.socket.off('player_died', onPlayerDied)
  props.socket.off('sentence_completed', onSentenceCompleted)
  props.socket.off('game_ended', onGameEnded)
})

const onLeaveClick = () => {
  emit('leave')
}
</script>

<template>
  <div :key="flashKey" class="terminal" :class="{ 'flash': mistypeFlash }">
    
    <div v-if="showAbortConfirm" class="confirm-overlay">
      <div class="confirm-dialog">
        <div class="confirm-title">ABORT MISSION?</div>
        <div class="confirm-message">
          This will stop the game for everyone and return to lobby.
          
          Continue?
        </div>
        <div class="confirm-actions">
          <button @click="confirmAbort" class="confirm-btn confirm-btn-ok">OK</button>
          <button @click="cancelAbort" class="confirm-btn confirm-btn-cancel">CANCEL</button>
        </div>
      </div>
    </div>

    <RouletteRevolver
      v-if="showRoulette && rouletteResult"
      :survived="rouletteResult.survived"
      :previousOdds="rouletteResult.previousOdds"
      :newOdds="rouletteResult.newOdds"
      :roll="rouletteResult.roll"
    />

    <div class="terminal-header">
      <div v-if="isSpectator && spectatorTarget" class="spectator-header-badge">
        SPECTATING: {{ spectatorTarget.nickname }}
      </div>
      <div v-else></div>

      <div class="header-right">
        <button v-if="isHost" @click="handleResetGame" class="term-btn-reset">ABORT</button>
        <button @click="onLeaveClick" class="term-btn">EXIT</button>
      </div>
    </div>

    <div class="terminal-body">
      <div class="typing-zone">
        
        <div v-if="status === 'DEAD' && !showRoulette" class="death-screen">
          <div class="death-text">
            <p>YOU ARE DEAD</p>
            <p>FINAL: {{ currentPlayer.completedSentences }}/{{ sentences.length }}</p>
            <p class="death-sub">[SPECTATING]</p>
          </div>
        </div>

        <div v-if="showVictory" class="victory-screen">
          <div class="victory-text">
            <p>MISSION COMPLETE</p>
            <p>SURVIVED: {{ currentPlayer.completedSentences }}/{{ sentences.length }}</p>
            <p class="victory-sub">[ANALYZING RESULTS]<span class="loading-dots"></span></p>
          </div>
        </div>

        <StatusHUD
          :remainingTime="isSpectator && spectatorTarget ? spectatorDisplayTime : remainingTime"
          :mistakeStrikes="isSpectator && spectatorTarget ? (spectatorTarget.mistakeStrikes || 0) : (currentPlayer.mistakeStrikes || 0)"
          :currentSentenceIndex="isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex"
          :totalSentences="sentences.length"
          :mistypeFlash="mistypeFlash"
        />

        <TypingField
          :key="`typing-${isSpectator && spectatorTarget ? spectatingPlayerId : playerId}-${isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex}`"
          :sentences="sentences"
          :currentSentenceIndex="isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex"
          :currentWordIndex="isSpectator && spectatorTarget ? (spectatorTarget.currentWordIndex || 0) : currentWordIndex"
          :currentCharInWord="isSpectator && spectatorTarget ? (spectatorTarget.currentCharInWord || 0) : currentCharInWord"
        />
      </div>

      <LeaderboardPanel
        :players="players"
        :playerId="playerId"
        :totalSentences="sentences.length"
        :onPlayerClick="isSpectator ? (id) => spectatingPlayerId = id : undefined"
        :highlightedPlayerId="isSpectator ? spectatingPlayerId : playerId"
      />
    </div>
  </div>
</template>

<style src="./GameScreen.css"></style>

// client/src/components/GameScreen.jsx
import React, { useState, useEffect, useRef } from 'react';
import './GameScreen.css';
import './RouletteRevolver.css';
import GameEndScreen from './GameEndScreen';
import GameController from './game/GameController';
import TypingField from './game/TypingField';
import StatusHUD from './game/StatusHUD';
import LeaderboardPanel from './game/LeaderboardPanel';

function RouletteRevolver({ survived, previousOdds, newOdds, roll }) {
  const [phase, setPhase] = useState('spinning');
  const [currentHighlight, setCurrentHighlight] = useState(null);
  
  useEffect(() => {
    const cylinderRef = document.querySelector('.revolver-cylinder');
    if (!cylinderRef) return;

    const targetChamber = roll - 1;
    const degreesPerChamber = 360 / previousOdds;
    
    const fullRotations = 3;
    const finalAngle = -(targetChamber * degreesPerChamber);
    const totalRotation = (fullRotations * 360) + finalAngle;
    
    cylinderRef.classList.add('spinning');
    
    let currentRotation = 0;
    const spinDuration = 2000;
    const startTime = Date.now();
    
    const spin = () => {
      const elapsed = Date.now() - startTime;
      const progress = Math.min(elapsed / spinDuration, 1);
      
      const easeProgress = 1 - Math.pow(1 - progress, 3);
      currentRotation = totalRotation * easeProgress;
      
      cylinderRef.style.transform = `translate(-50%, -50%) rotate(${currentRotation}deg)`;
      
      const normalizedRotation = ((currentRotation % 360) + 360) % 360;
      const currentChamberIndex = Math.round(normalizedRotation / degreesPerChamber) % previousOdds;
      setCurrentHighlight((previousOdds - currentChamberIndex) % previousOdds);
      
      if (progress < 1) {
        requestAnimationFrame(spin);
      } else {
        cylinderRef.classList.remove('spinning');
        setPhase('stopped');
        setCurrentHighlight(targetChamber);
        
        setTimeout(() => {
          setPhase('result');
        }, 450);
      }
    };
    
    setTimeout(() => {
      requestAnimationFrame(spin);
    }, 200);

  }, [roll, previousOdds]);

  const chambers = Array.from({ length: previousOdds }, (_, i) => ({
    isBullet: i === 0,
    index: i
  }));

  const degreesPerChamber = 360 / previousOdds;

  return (
    <div className="roulette-overlay">
      <div className="revolver-container">
        <div className="revolver-title">JUDGMENT</div>
        
        <div className="revolver-chamber-area">
          <div className="revolver-hammer">▼</div>
          
          <div className="revolver-cylinder">
            {chambers.map((chamber, i) => {
              const angle = i * degreesPerChamber;
              const radius = 100;
              const x = Math.sin((angle * Math.PI) / 180) * radius;
              const y = -Math.cos((angle * Math.PI) / 180) * radius;
              
              const isHighlighted = i === currentHighlight;
              
              return (
                <div
                  key={i}
                  className={`chamber ${isHighlighted ? 'highlighted' : ''} ${chamber.isBullet ? 'bullet-chamber' : 'empty-chamber'}`}
                  style={{
                    left: `calc(50% + ${x}px)`,
                    top: `calc(50% + ${y}px)`
                  }}
                />
              );
            })}
          </div>
        </div>

        {phase === 'result' && (
          <div className={`revolver-result ${survived ? 'survived' : 'died'}`}>
            <div className="result-text">
              {survived ? 'CLICK!' : 'BANG!'}
            </div>
            <div className="result-odds">
              {survived 
                ? `1/${previousOdds} → 1/${newOdds}` 
                : `1/${previousOdds}`
              }
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function GameScreen({ socket, room, playerId, sentences, onLeave, isSpectator = false }) {
  const [currentSentenceIndex, setCurrentSentenceIndex] = useState(0);
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [currentCharInWord, setCurrentCharInWord] = useState(0);
  const [remainingTime, setRemainingTime] = useState(20);
  const [status, setStatus] = useState('ALIVE');
  const [players, setPlayers] = useState(room.players);
  const [mistypeFlash, setMistypeFlash] = useState(false);
  const [flashKey, setFlashKey] = useState(0);
  const [showRoulette, setShowRoulette] = useState(false);
  const [rouletteResult, setRouletteResult] = useState(null);
  const [isProcessingError, setIsProcessingError] = useState(false);
  const [showVictory, setShowVictory] = useState(false);
  const [showAbortConfirm, setShowAbortConfirm] = useState(false);
  const rouletteActiveRef = useRef(false);
  
  const currentSentence = sentences[currentSentenceIndex] || '';
  const words = currentSentence.split(' ');
  const currentWord = words[currentWordIndex] || '';
  const currentPlayer = players[playerId] || {};
  const [spectatingPlayerId, setSpectatingPlayerId] = useState(null);
  const spectatorTarget = isSpectator && spectatingPlayerId ? players[spectatingPlayerId] : null;
  const isHost = room.hostId === playerId;

  const handleResetGame = () => {
    if (!isHost) return;
    setShowAbortConfirm(true);
  };

  const confirmAbort = () => {
    socket.emit('force_reset_game', { roomCode: room.roomCode }, (response) => {
      if (!response.success) {
        console.error('Failed to reset game:', response.error);
      }
    });
    setShowAbortConfirm(false);
  };

  const cancelAbort = () => {
    setShowAbortConfirm(false);
  };

  useEffect(() => {
    if (isSpectator) return;
    if (status !== 'ALIVE') return;

    const interval = setInterval(() => {
      setRemainingTime(prev => {
        const newTime = Math.max(0, prev - 0.1);
        if (newTime <= 0 && prev > 0) {
          socket.emit('sentence_timeout', {
            roomCode: room.roomCode,
            sentenceIndex: currentSentenceIndex
          });
        }
        return newTime;
      });
    }, 100);

    return () => clearInterval(interval);
  }, [status, currentSentenceIndex, socket, room.roomCode, isSpectator]);

  useEffect(() => {
    if (!isSpectator || !spectatorTarget || spectatorTarget.status !== 'ALIVE') return;
    if (!spectatorTarget.sentenceStartTime) return;

    const interval = setInterval(() => {
      const elapsed = (Date.now() - spectatorTarget.sentenceStartTime) / 1000;
      const calculated = Math.max(0, 20 - elapsed);
      
      setPlayers(prev => ({
        ...prev,
        [spectatingPlayerId]: {
          ...prev[spectatingPlayerId],
          calculatedTime: calculated
        }
      }));
    }, 100);

    return () => clearInterval(interval);
  }, [isSpectator, spectatorTarget?.sentenceStartTime, spectatingPlayerId]);

  useEffect(() => {
    if (status !== 'ALIVE' || isProcessingError || isSpectator) return;

    const handleKeyPress = (e) => {
      e.preventDefault();
      const key = e.key;

      if (GameController.isNavigationKey(key) && key !== ' ') return;

      const words = currentSentence.split(' ');
      const currentWord = words[currentWordIndex] || '';
      const charIndex = GameController.calculateGlobalCharIndex(words, currentWordIndex, currentCharInWord);

      if (key === ' ') {
        if (GameController.shouldAdvanceWord(currentCharInWord, currentWord)) {
          if (currentWordIndex < words.length - 1) {
            setCurrentWordIndex(prev => prev + 1);
            setCurrentCharInWord(0);
            
            socket.emit('char_typed', {
              roomCode: room.roomCode,
              char: ' ',
              charIndex: charIndex,
              timestamp: Date.now()
            });
          }
        } else {
          setIsProcessingError(true);
          socket.emit('mistype', {
            roomCode: room.roomCode,
            expectedChar: currentWord[currentCharInWord],
            typedChar: key,
            charIndex: charIndex,
            sentenceIndex: currentSentenceIndex
          });
          setCurrentWordIndex(0);
          setCurrentCharInWord(0);
        }
        return;
      }

      const expectedChar = currentWord[currentCharInWord];

      if (GameController.validateChar(key, expectedChar)) {
        const newCharInWord = currentCharInWord + 1;
        setCurrentCharInWord(newCharInWord);

        socket.emit('char_typed', {
          roomCode: room.roomCode,
          char: key,
          charIndex: charIndex,
          timestamp: Date.now()
        });

        if (GameController.shouldCompleteSentence(currentWordIndex, words, newCharInWord, currentWord)) {
          setTimeout(() => {
            const nextIndex = currentSentenceIndex + 1;
            if (nextIndex < sentences.length) {
              setCurrentSentenceIndex(nextIndex);
              setCurrentWordIndex(0);
              setCurrentCharInWord(0);
              setRemainingTime(20);
            }
          }, 100);
        }
      } else {
        setIsProcessingError(true);
        socket.emit('mistype', {
          roomCode: room.roomCode,
          expectedChar: expectedChar,
          typedChar: key,
          charIndex: charIndex,
          sentenceIndex: currentSentenceIndex
        });
        setCurrentWordIndex(0);
        setCurrentCharInWord(0);
      }
    };

    document.addEventListener('keydown', handleKeyPress);
    return () => document.removeEventListener('keydown', handleKeyPress);
  }, [status, isProcessingError, isSpectator, currentCharInWord, currentWord, currentWordIndex, words, currentSentenceIndex, socket, room.roomCode, sentences.length]);

  useEffect(() => {
    if (isSpectator && !spectatingPlayerId && players) {
      const alivePlayers = Object.values(players).filter(p => p.status === 'ALIVE');
      if (alivePlayers.length > 0) {
        setSpectatingPlayerId(alivePlayers[0].id);
        console.log(`Auto-spectating: ${alivePlayers[0].nickname}`);
      }
    }
  }, [isSpectator, spectatingPlayerId, players]);

  useEffect(() => {
    const handlePlayerProgress = (data) => {
      setPlayers(prev => ({
        ...prev,
        [data.playerId]: {
          ...prev[data.playerId],
          currentCharIndex: data.charIndex,
          currentSentenceIndex: data.sentenceIndex,
          currentWordIndex: data.currentWordIndex || 0,
          currentCharInWord: data.currentCharInWord || 0,
          completedSentences: data.completedSentences,
          totalCorrectChars: data.totalCorrectChars,
          totalTypedChars: data.totalTypedChars,
          totalMistypes: data.totalMistypes,
          averageWPM: data.wpm,
          status: data.status,
          sentenceStartTime: data.sentenceStartTime
        }
      }));
    };

    const handlePlayerStrike = (data) => {
      setPlayers(prev => ({
        ...prev,
        [data.playerId]: {
          ...prev[data.playerId],
          mistakeStrikes: data.strikes,
          sentenceStartTime: data.sentenceStartTime,
          currentWordIndex: data.currentWordIndex,
          currentCharInWord: data.currentCharInWord,
          currentCharIndex: data.currentCharIndex
        }
      }));

      if (data.playerId === playerId) {
        setMistypeFlash(true);
        setFlashKey(prev => prev + 1);
        setRemainingTime(20);
        setTimeout(() => {
          setMistypeFlash(false);
        }, 300);

        if (data.strikes < 3) {
          setTimeout(() => {
            setIsProcessingError(false);
          }, 300);
        }
      }
    };

    const handleRouletteResult = (data) => {
      if (isSpectator && data.playerId === spectatingPlayerId) {
        console.log(`🎰 Spectator seeing roulette for ${players[data.playerId]?.nickname}`);
        setShowRoulette(true);
        setRouletteResult(data);
        
        if (data.survived) {
          setPlayers(prev => ({
            ...prev,
            [data.playerId]: {
              ...prev[data.playerId],
              rouletteOdds: data.newOdds,
              mistakeStrikes: 0,
              sentenceStartTime: data.sentenceStartTime
            }
          }));
        }
        
        setTimeout(() => {
          setShowRoulette(false);
          setRouletteResult(null);
        }, 4500);
      }
      
      if (data.playerId === playerId) {
        rouletteActiveRef.current = true;
        
        setShowRoulette(true);
        setRouletteResult(data);

        if (!data.survived) {
          setStatus('DEAD');
        }
        
        setPlayers(prev => ({
          ...prev,
          [data.playerId]: {
            ...prev[data.playerId],
            rouletteOdds: data.newOdds,
            mistakeStrikes: data.survived ? 0 : prev[data.playerId].mistakeStrikes,
            sentenceStartTime: data.survived ? data.sentenceStartTime : prev[data.playerId].sentenceStartTime
          }
        }));
        
        setTimeout(() => {
          setShowRoulette(false);
          setRouletteResult(null);
          rouletteActiveRef.current = false;
          
          if (data.survived) {
            setCurrentWordIndex(0);
            setCurrentCharInWord(0);
            setRemainingTime(20);
            setIsProcessingError(false);
          }
        }, 4500);
      } else {
        setPlayers(prev => ({
          ...prev,
          [data.playerId]: {
            ...prev[data.playerId],
            rouletteOdds: data.newOdds,
            mistakeStrikes: data.survived ? 0 : prev[data.playerId].mistakeStrikes,
            sentenceStartTime: data.survived ? data.sentenceStartTime : prev[data.playerId].sentenceStartTime
          }
        }));
      }
    };

    const handlePlayerDied = (data) => {
      setPlayers(prev => ({
        ...prev,
        [data.playerId]: {
          ...prev[data.playerId],
          status: 'DEAD'
        }
      }));

      if (data.playerId === playerId && data.deathReason !== 'MISTYPE' && data.deathReason !== 'TIMEOUT') {
        setStatus('DEAD');
      }
    };

    const handleSentenceCompleted = (data) => {
      setPlayers(prev => {
        const updated = {
          ...prev,
          [data.playerId]: {
            ...prev[data.playerId],
            completedSentences: (prev[data.playerId].completedSentences || 0) + 1,
            currentSentenceIndex: data.newSentenceIndex,
            sentenceStartTime: data.sentenceStartTime,
            currentWordIndex: 0,
            currentCharInWord: 0,
            currentCharIndex: 0
          }
        };

        if (isSpectator && data.playerId === spectatingPlayerId) {
          console.log(`🎯 Spectator sees sentence complete for ${prev[data.playerId]?.nickname}`);
          console.log(`  → Sentence ${prev[data.playerId]?.currentSentenceIndex} → ${data.newSentenceIndex}`);
          console.log(`  → Reset indices to 0`);
        }

        return updated;
      });
    };

    const handleGameEnded = (data) => {
      console.log('🏁 Game ended event received:', data);
      setPlayers(prev => {
        const updatedPlayers = { ...prev };
        Object.keys(data.finalStats).forEach(pId => {
          updatedPlayers[pId] = {
            ...updatedPlayers[pId],
            ...data.finalStats[pId]
          };
        });
        return updatedPlayers;
      });
      
      if (data.winnerId === playerId && data.reason === 'COMPLETION') {
        setShowVictory(true);
      }
    };

    socket.on('player_progress', handlePlayerProgress);
    socket.on('player_strike', handlePlayerStrike);
    socket.on('roulette_result', handleRouletteResult);
    socket.on('player_died', handlePlayerDied);
    socket.on('sentence_completed', handleSentenceCompleted);
    socket.on('game_ended', handleGameEnded);

    return () => {
      socket.off('player_progress', handlePlayerProgress);
      socket.off('player_strike', handlePlayerStrike);
      socket.off('roulette_result', handleRouletteResult);
      socket.off('player_died', handlePlayerDied);
      socket.off('sentence_completed', handleSentenceCompleted);
      socket.off('game_ended', handleGameEnded);
    };
  }, [socket, playerId, showRoulette, status, isSpectator, spectatingPlayerId, players]);

  const sortedPlayers = Object.values(players).sort((a, b) => {
    if (a.status === 'ALIVE' && b.status !== 'ALIVE') return -1;
    if (a.status !== 'ALIVE' && b.status === 'ALIVE') return 1;
    if (b.completedSentences !== a.completedSentences) {
      return b.completedSentences - a.completedSentences;
    }
    return b.totalCorrectChars - a.totalCorrectChars;
  });

  const spectatorDisplayTime = spectatorTarget?.calculatedTime ?? 20;

  return (
    <div key={flashKey} className={`terminal ${mistypeFlash ? 'flash' : ''}`}>
      {showAbortConfirm && (
        <div className="confirm-overlay">
          <div className="confirm-dialog">
            <div className="confirm-title">ABORT MISSION?</div>
            <div className="confirm-message">
              This will stop the game for everyone and return to lobby.
              
              Continue?
            </div>
            <div className="confirm-actions">
              <button onClick={confirmAbort} className="confirm-btn confirm-btn-ok">
                OK
              </button>
              <button onClick={cancelAbort} className="confirm-btn confirm-btn-cancel">
                CANCEL
              </button>
            </div>
          </div>
        </div>
      )}

      {showRoulette && rouletteResult && (
        <RouletteRevolver 
          survived={rouletteResult.survived}
          previousOdds={rouletteResult.previousOdds}
          newOdds={rouletteResult.newOdds}
          roll={rouletteResult.roll}
        />
      )}

      <div className="terminal-header">
        {isSpectator && spectatorTarget ? (
          <div className="spectator-header-badge">
            SPECTATING: {spectatorTarget.nickname}
          </div>
        ) : (
          <div></div>
        )}
        <div className="header-right">
          {isHost && (
            <button onClick={handleResetGame} className="term-btn-reset">
              ABORT
            </button>
          )}
          <button onClick={onLeave} className="term-btn">EXIT</button>
        </div>
      </div>

      <div className="terminal-body">
        <div className="typing-zone">
          {status === 'DEAD' && !showRoulette && (
            <div className="death-screen">
              <div className="death-text">
                <p>YOU ARE DEAD</p>
                <p>FINAL: {currentPlayer.completedSentences}/{sentences.length}</p>
                <p className="death-sub">[SPECTATING]</p>
              </div>
            </div>
          )}

          {showVictory && (
            <div className="victory-screen">
              <div className="victory-text">
                <p>MISSION COMPLETE</p>
                <p>SURVIVED: {currentPlayer.completedSentences}/{sentences.length}</p>
                <p className="victory-sub">[ANALYZING RESULTS]<span className="loading-dots" /></p>
              </div>
            </div>
          )}

          <StatusHUD
            remainingTime={isSpectator && spectatorTarget ? spectatorDisplayTime : remainingTime}
            mistakeStrikes={isSpectator && spectatorTarget ? (spectatorTarget.mistakeStrikes || 0) : (currentPlayer.mistakeStrikes || 0)}
            currentSentenceIndex={isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex}
            totalSentences={sentences.length}
            mistypeFlash={mistypeFlash}
          />

          <TypingField
            key={`typing-${isSpectator && spectatorTarget ? spectatingPlayerId : playerId}-${isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex}`}
            sentences={sentences}
            currentSentenceIndex={isSpectator && spectatorTarget ? (spectatorTarget.currentSentenceIndex || 0) : currentSentenceIndex}
            currentWordIndex={isSpectator && spectatorTarget ? (spectatorTarget.currentWordIndex || 0) : currentWordIndex}
            currentCharInWord={isSpectator && spectatorTarget ? (spectatorTarget.currentCharInWord || 0) : currentCharInWord}
          />
        </div>

        <LeaderboardPanel
          players={players}
          playerId={playerId}
          totalSentences={sentences.length}
          onPlayerClick={isSpectator ? setSpectatingPlayerId : undefined}
          highlightedPlayerId={isSpectator ? spectatingPlayerId : playerId}
        />
      </div>
    </div>
  );
}

export default GameScreen;
